spring.application.name=backendnourpfe
server.servlet.context-path=/nour
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/backendnourpfe?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
upload.directory=${UPLOAD_DIRECTORY:C:/xampppidev/htdocs/img/}

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.servlet.multipart.enabled=true

logging.level.org.springframework.web.socket=DEBUG
logging.level.org.springframework.messaging=DEBUG


application.security.jwt.secret-key=pXk9AZv+L8syrTyRSWuV/zsbW9iycEclGFtjasEXc4SCW/eI6mFcnKOuFMPdjyjhTX5r0Wez+8ZtX23xwpBgle1Odb66/gQDrax5rBwh3xo=

application.security.jwt.expiration= 86400000   
application.security.jwt.refresh-token.expiration= 604800000 # 7 days
spring.mvc.pathmatch.matching-strategy=ant-path-matcher
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=nourlass50@gmail.com
spring.mail.password=qwua jsrz pfzo kvkq
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.auth=true
server.port=8088



spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=2MB

flouci.public-token=8308c8a4-92ab-458b-81c0-32d2185e21d0
flouci.private-token=07ff7e6f-a22b-40ed-aab8-21b424f9350b


management.endpoint.prometheus.enabled=true
management.endpoints.web.base-path=/actuator
management.prometheus.metrics.export.enabled=true

management.server.port=8089
management.endpoints.web.exposure.include=health,info


