name: Build and Push on GitHub Packages

on:
  push:
    tags:
      - "*v*.*.*"  # exemple: v1.0.0, v2.5.3

jobs:
  build_push_github_packages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/nourlassoued/nourangular
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
         
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CHCR_TOKEN }}
      
      - name: Build and Push Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Checkout argocdpfe  repo
        uses: actions/checkout@v4
        with:          

          repository: nourlassoued/argocdpfe 
          ref: master
          token: ${{ secrets.CHCR_TOKEN }}
          path: argocdpfe 

      - name: Update image tag in angular.yml
        run: |
          IMAGE_TAG="1.1.${{ github.run_number }}"
          sed -i "s|image: nourlassoued/nourangular:.*|image: nourlassoued/nourangular:${IMAGE_TAG}|" argocdpfe/angular-app/angular.yml

      - name: Commit and push changes to argocdpfe repo
        run: |
          cd argocdpfe
          git config user.name "GitHub Actions"
          git config user.email "github-action@github.com"
          git add angular-app/angular.yml
          git commit -m "Update Docker image tag to 1.1.${{ github.run_number }}"
          git push
